// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "medicines")
public class Medicine {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotBlank
    @Column(nullable = false)
    private String name;
    @Column(length = 1000)
    private String description;
    @Column(nullable = false)
    private String dosage;
    @Column(name = "dosage_unit")
    private String dosageUnit;
    @Enumerated(EnumType.STRING)
    @Column(name = "medicine_type")
    private MedicineType medicineType;
    @Column(name = "manufacturer")
    private String manufacturer;
    @Column(name = "batch_number")
    private String batchNumber;
    @Column(name = "expiry_date")
    private LocalDate expiryDate;
    @Column(name = "purchase_date")
    private LocalDate purchaseDate;
    @Positive
    @Column(name = "quantity")
    private Integer quantity;
    @Column(name = "quantity_unit")
    private String quantityUnit;
    @Column(name = "low_stock_threshold")
    private Integer lowStockThreshold;
    @Column(name = "price")
    private Double price;
    @Column(name = "prescription_required")
    private boolean prescriptionRequired;
    @Column(name = "side_effects", length = 2000)
    private String sideEffects;
    @Column(name = "storage_instructions")
    private String storageInstructions;
    @Column(name = "image_url")
    private String imageUrl;
    @Column(name = "barcode")
    private String barcode;
    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    private MedicineStatus status;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @OneToMany(mappedBy = "medicine", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Reminder> reminders;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;


    public enum MedicineType {
        TABLET, CAPSULE, SYRUP, INJECTION, CREAM, DROPS, INHALER, PATCH, POWDER, OTHER;
    }


    public enum MedicineStatus {
        ACTIVE, EXPIRED, LOW_STOCK, OUT_OF_STOCK, DISCONTINUED;
    }

    public boolean isExpired() {
        return expiryDate != null && expiryDate.isBefore(LocalDate.now());
    }

    public boolean isLowStock() {
        return quantity != null && lowStockThreshold != null && quantity <= lowStockThreshold;
    }

    @java.lang.SuppressWarnings("all")
    private static Integer $default$lowStockThreshold() {
        return 5;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$prescriptionRequired() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    private static MedicineStatus $default$status() {
        return MedicineStatus.ACTIVE;
    }

    @java.lang.SuppressWarnings("all")
    private static List<Reminder> $default$reminders() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    public static class MedicineBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String name;
        @java.lang.SuppressWarnings("all")
        private String description;
        @java.lang.SuppressWarnings("all")
        private String dosage;
        @java.lang.SuppressWarnings("all")
        private String dosageUnit;
        @java.lang.SuppressWarnings("all")
        private MedicineType medicineType;
        @java.lang.SuppressWarnings("all")
        private String manufacturer;
        @java.lang.SuppressWarnings("all")
        private String batchNumber;
        @java.lang.SuppressWarnings("all")
        private LocalDate expiryDate;
        @java.lang.SuppressWarnings("all")
        private LocalDate purchaseDate;
        @java.lang.SuppressWarnings("all")
        private Integer quantity;
        @java.lang.SuppressWarnings("all")
        private String quantityUnit;
        @java.lang.SuppressWarnings("all")
        private boolean lowStockThreshold$set;
        @java.lang.SuppressWarnings("all")
        private Integer lowStockThreshold$value;
        @java.lang.SuppressWarnings("all")
        private Double price;
        @java.lang.SuppressWarnings("all")
        private boolean prescriptionRequired$set;
        @java.lang.SuppressWarnings("all")
        private boolean prescriptionRequired$value;
        @java.lang.SuppressWarnings("all")
        private String sideEffects;
        @java.lang.SuppressWarnings("all")
        private String storageInstructions;
        @java.lang.SuppressWarnings("all")
        private String imageUrl;
        @java.lang.SuppressWarnings("all")
        private String barcode;
        @java.lang.SuppressWarnings("all")
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        private MedicineStatus status$value;
        @java.lang.SuppressWarnings("all")
        private User user;
        @java.lang.SuppressWarnings("all")
        private boolean reminders$set;
        @java.lang.SuppressWarnings("all")
        private List<Reminder> reminders$value;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        MedicineBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder dosage(final String dosage) {
            this.dosage = dosage;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder dosageUnit(final String dosageUnit) {
            this.dosageUnit = dosageUnit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder medicineType(final MedicineType medicineType) {
            this.medicineType = medicineType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder manufacturer(final String manufacturer) {
            this.manufacturer = manufacturer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder batchNumber(final String batchNumber) {
            this.batchNumber = batchNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder expiryDate(final LocalDate expiryDate) {
            this.expiryDate = expiryDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder purchaseDate(final LocalDate purchaseDate) {
            this.purchaseDate = purchaseDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder quantity(final Integer quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder quantityUnit(final String quantityUnit) {
            this.quantityUnit = quantityUnit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder lowStockThreshold(final Integer lowStockThreshold) {
            this.lowStockThreshold$value = lowStockThreshold;
            lowStockThreshold$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder price(final Double price) {
            this.price = price;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder prescriptionRequired(final boolean prescriptionRequired) {
            this.prescriptionRequired$value = prescriptionRequired;
            prescriptionRequired$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder sideEffects(final String sideEffects) {
            this.sideEffects = sideEffects;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder storageInstructions(final String storageInstructions) {
            this.storageInstructions = storageInstructions;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder barcode(final String barcode) {
            this.barcode = barcode;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder status(final MedicineStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder reminders(final List<Reminder> reminders) {
            this.reminders$value = reminders;
            reminders$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Medicine.MedicineBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Medicine build() {
            Integer lowStockThreshold$value = this.lowStockThreshold$value;
            if (!this.lowStockThreshold$set) lowStockThreshold$value = Medicine.$default$lowStockThreshold();
            boolean prescriptionRequired$value = this.prescriptionRequired$value;
            if (!this.prescriptionRequired$set) prescriptionRequired$value = Medicine.$default$prescriptionRequired();
            MedicineStatus status$value = this.status$value;
            if (!this.status$set) status$value = Medicine.$default$status();
            List<Reminder> reminders$value = this.reminders$value;
            if (!this.reminders$set) reminders$value = Medicine.$default$reminders();
            return new Medicine(this.id, this.name, this.description, this.dosage, this.dosageUnit, this.medicineType, this.manufacturer, this.batchNumber, this.expiryDate, this.purchaseDate, this.quantity, this.quantityUnit, lowStockThreshold$value, this.price, prescriptionRequired$value, this.sideEffects, this.storageInstructions, this.imageUrl, this.barcode, status$value, this.user, reminders$value, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Medicine.MedicineBuilder(id=" + this.id + ", name=" + this.name + ", description=" + this.description + ", dosage=" + this.dosage + ", dosageUnit=" + this.dosageUnit + ", medicineType=" + this.medicineType + ", manufacturer=" + this.manufacturer + ", batchNumber=" + this.batchNumber + ", expiryDate=" + this.expiryDate + ", purchaseDate=" + this.purchaseDate + ", quantity=" + this.quantity + ", quantityUnit=" + this.quantityUnit + ", lowStockThreshold$value=" + this.lowStockThreshold$value + ", price=" + this.price + ", prescriptionRequired$value=" + this.prescriptionRequired$value + ", sideEffects=" + this.sideEffects + ", storageInstructions=" + this.storageInstructions + ", imageUrl=" + this.imageUrl + ", barcode=" + this.barcode + ", status$value=" + this.status$value + ", user=" + this.user + ", reminders$value=" + this.reminders$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Medicine.MedicineBuilder builder() {
        return new Medicine.MedicineBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getDosage() {
        return this.dosage;
    }

    @java.lang.SuppressWarnings("all")
    public String getDosageUnit() {
        return this.dosageUnit;
    }

    @java.lang.SuppressWarnings("all")
    public MedicineType getMedicineType() {
        return this.medicineType;
    }

    @java.lang.SuppressWarnings("all")
    public String getManufacturer() {
        return this.manufacturer;
    }

    @java.lang.SuppressWarnings("all")
    public String getBatchNumber() {
        return this.batchNumber;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getExpiryDate() {
        return this.expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getPurchaseDate() {
        return this.purchaseDate;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    public String getQuantityUnit() {
        return this.quantityUnit;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getLowStockThreshold() {
        return this.lowStockThreshold;
    }

    @java.lang.SuppressWarnings("all")
    public Double getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isPrescriptionRequired() {
        return this.prescriptionRequired;
    }

    @java.lang.SuppressWarnings("all")
    public String getSideEffects() {
        return this.sideEffects;
    }

    @java.lang.SuppressWarnings("all")
    public String getStorageInstructions() {
        return this.storageInstructions;
    }

    @java.lang.SuppressWarnings("all")
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getBarcode() {
        return this.barcode;
    }

    @java.lang.SuppressWarnings("all")
    public MedicineStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public List<Reminder> getReminders() {
        return this.reminders;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setDosage(final String dosage) {
        this.dosage = dosage;
    }

    @java.lang.SuppressWarnings("all")
    public void setDosageUnit(final String dosageUnit) {
        this.dosageUnit = dosageUnit;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicineType(final MedicineType medicineType) {
        this.medicineType = medicineType;
    }

    @java.lang.SuppressWarnings("all")
    public void setManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @java.lang.SuppressWarnings("all")
    public void setBatchNumber(final String batchNumber) {
        this.batchNumber = batchNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiryDate(final LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setPurchaseDate(final LocalDate purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuantityUnit(final String quantityUnit) {
        this.quantityUnit = quantityUnit;
    }

    @java.lang.SuppressWarnings("all")
    public void setLowStockThreshold(final Integer lowStockThreshold) {
        this.lowStockThreshold = lowStockThreshold;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrice(final Double price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrescriptionRequired(final boolean prescriptionRequired) {
        this.prescriptionRequired = prescriptionRequired;
    }

    @java.lang.SuppressWarnings("all")
    public void setSideEffects(final String sideEffects) {
        this.sideEffects = sideEffects;
    }

    @java.lang.SuppressWarnings("all")
    public void setStorageInstructions(final String storageInstructions) {
        this.storageInstructions = storageInstructions;
    }

    @java.lang.SuppressWarnings("all")
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setBarcode(final String barcode) {
        this.barcode = barcode;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final MedicineStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setReminders(final List<Reminder> reminders) {
        this.reminders = reminders;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public Medicine() {
        this.lowStockThreshold = Medicine.$default$lowStockThreshold();
        this.prescriptionRequired = Medicine.$default$prescriptionRequired();
        this.status = Medicine.$default$status();
        this.reminders = Medicine.$default$reminders();
    }

    @java.lang.SuppressWarnings("all")
    public Medicine(final Long id, final String name, final String description, final String dosage, final String dosageUnit, final MedicineType medicineType, final String manufacturer, final String batchNumber, final LocalDate expiryDate, final LocalDate purchaseDate, final Integer quantity, final String quantityUnit, final Integer lowStockThreshold, final Double price, final boolean prescriptionRequired, final String sideEffects, final String storageInstructions, final String imageUrl, final String barcode, final MedicineStatus status, final User user, final List<Reminder> reminders, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.dosage = dosage;
        this.dosageUnit = dosageUnit;
        this.medicineType = medicineType;
        this.manufacturer = manufacturer;
        this.batchNumber = batchNumber;
        this.expiryDate = expiryDate;
        this.purchaseDate = purchaseDate;
        this.quantity = quantity;
        this.quantityUnit = quantityUnit;
        this.lowStockThreshold = lowStockThreshold;
        this.price = price;
        this.prescriptionRequired = prescriptionRequired;
        this.sideEffects = sideEffects;
        this.storageInstructions = storageInstructions;
        this.imageUrl = imageUrl;
        this.barcode = barcode;
        this.status = status;
        this.user = user;
        this.reminders = reminders;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
