// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "reminders")
public class Reminder {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "title", nullable = false)
    private String title;
    @Column(name = "notes", length = 1000)
    private String notes;
    @Enumerated(EnumType.STRING)
    @Column(name = "frequency", nullable = false)
    private Frequency frequency;
    @ElementCollection
    @CollectionTable(name = "reminder_times", joinColumns = @JoinColumn(name = "reminder_id"))
    @Column(name = "reminder_time")
    private List<LocalTime> reminderTimes;
    @ElementCollection
    @CollectionTable(name = "reminder_days", joinColumns = @JoinColumn(name = "reminder_id"))
    @Enumerated(EnumType.STRING)
    @Column(name = "day_of_week")
    private List<DayOfWeek> daysOfWeek;
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;
    @Column(name = "end_date")
    private LocalDate endDate;
    @Column(name = "dose_amount")
    private Double doseAmount;
    @Column(name = "dose_unit")
    private String doseUnit;
    @Enumerated(EnumType.STRING)
    @Column(name = "notification_type")
    private NotificationType notificationType;
    @Column(name = "is_active")
    private boolean active;
    @Column(name = "is_completed")
    private boolean completed;
    @Column(name = "last_taken_at")
    private LocalDateTime lastTakenAt;
    @Column(name = "snooze_minutes")
    private Integer snoozeMinutes;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medicine_id")
    private Medicine medicine;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;


    public enum Frequency {
        ONCE, DAILY, TWICE_DAILY, THREE_TIMES_DAILY, WEEKLY, MONTHLY, CUSTOM;
    }


    public enum DayOfWeek {
        MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY;
    }


    public enum NotificationType {
        PUSH, EMAIL, SMS, ALL;
    }

    @java.lang.SuppressWarnings("all")
    private static List<LocalTime> $default$reminderTimes() {
        return new ArrayList<>();
    }

    @java.lang.SuppressWarnings("all")
    private static List<DayOfWeek> $default$daysOfWeek() {
        return new ArrayList<>();
    }

    @java.lang.SuppressWarnings("all")
    private static NotificationType $default$notificationType() {
        return NotificationType.PUSH;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$active() {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$completed() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    private static Integer $default$snoozeMinutes() {
        return 10;
    }


    @java.lang.SuppressWarnings("all")
    public static class ReminderBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String title;
        @java.lang.SuppressWarnings("all")
        private String notes;
        @java.lang.SuppressWarnings("all")
        private Frequency frequency;
        @java.lang.SuppressWarnings("all")
        private boolean reminderTimes$set;
        @java.lang.SuppressWarnings("all")
        private List<LocalTime> reminderTimes$value;
        @java.lang.SuppressWarnings("all")
        private boolean daysOfWeek$set;
        @java.lang.SuppressWarnings("all")
        private List<DayOfWeek> daysOfWeek$value;
        @java.lang.SuppressWarnings("all")
        private LocalDate startDate;
        @java.lang.SuppressWarnings("all")
        private LocalDate endDate;
        @java.lang.SuppressWarnings("all")
        private Double doseAmount;
        @java.lang.SuppressWarnings("all")
        private String doseUnit;
        @java.lang.SuppressWarnings("all")
        private boolean notificationType$set;
        @java.lang.SuppressWarnings("all")
        private NotificationType notificationType$value;
        @java.lang.SuppressWarnings("all")
        private boolean active$set;
        @java.lang.SuppressWarnings("all")
        private boolean active$value;
        @java.lang.SuppressWarnings("all")
        private boolean completed$set;
        @java.lang.SuppressWarnings("all")
        private boolean completed$value;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime lastTakenAt;
        @java.lang.SuppressWarnings("all")
        private boolean snoozeMinutes$set;
        @java.lang.SuppressWarnings("all")
        private Integer snoozeMinutes$value;
        @java.lang.SuppressWarnings("all")
        private User user;
        @java.lang.SuppressWarnings("all")
        private Medicine medicine;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        ReminderBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder frequency(final Frequency frequency) {
            this.frequency = frequency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder reminderTimes(final List<LocalTime> reminderTimes) {
            this.reminderTimes$value = reminderTimes;
            reminderTimes$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder daysOfWeek(final List<DayOfWeek> daysOfWeek) {
            this.daysOfWeek$value = daysOfWeek;
            daysOfWeek$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder startDate(final LocalDate startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder endDate(final LocalDate endDate) {
            this.endDate = endDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder doseAmount(final Double doseAmount) {
            this.doseAmount = doseAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder doseUnit(final String doseUnit) {
            this.doseUnit = doseUnit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder notificationType(final NotificationType notificationType) {
            this.notificationType$value = notificationType;
            notificationType$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder active(final boolean active) {
            this.active$value = active;
            active$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder completed(final boolean completed) {
            this.completed$value = completed;
            completed$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder lastTakenAt(final LocalDateTime lastTakenAt) {
            this.lastTakenAt = lastTakenAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder snoozeMinutes(final Integer snoozeMinutes) {
            this.snoozeMinutes$value = snoozeMinutes;
            snoozeMinutes$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder medicine(final Medicine medicine) {
            this.medicine = medicine;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Reminder.ReminderBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Reminder build() {
            List<LocalTime> reminderTimes$value = this.reminderTimes$value;
            if (!this.reminderTimes$set) reminderTimes$value = Reminder.$default$reminderTimes();
            List<DayOfWeek> daysOfWeek$value = this.daysOfWeek$value;
            if (!this.daysOfWeek$set) daysOfWeek$value = Reminder.$default$daysOfWeek();
            NotificationType notificationType$value = this.notificationType$value;
            if (!this.notificationType$set) notificationType$value = Reminder.$default$notificationType();
            boolean active$value = this.active$value;
            if (!this.active$set) active$value = Reminder.$default$active();
            boolean completed$value = this.completed$value;
            if (!this.completed$set) completed$value = Reminder.$default$completed();
            Integer snoozeMinutes$value = this.snoozeMinutes$value;
            if (!this.snoozeMinutes$set) snoozeMinutes$value = Reminder.$default$snoozeMinutes();
            return new Reminder(this.id, this.title, this.notes, this.frequency, reminderTimes$value, daysOfWeek$value, this.startDate, this.endDate, this.doseAmount, this.doseUnit, notificationType$value, active$value, completed$value, this.lastTakenAt, snoozeMinutes$value, this.user, this.medicine, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Reminder.ReminderBuilder(id=" + this.id + ", title=" + this.title + ", notes=" + this.notes + ", frequency=" + this.frequency + ", reminderTimes$value=" + this.reminderTimes$value + ", daysOfWeek$value=" + this.daysOfWeek$value + ", startDate=" + this.startDate + ", endDate=" + this.endDate + ", doseAmount=" + this.doseAmount + ", doseUnit=" + this.doseUnit + ", notificationType$value=" + this.notificationType$value + ", active$value=" + this.active$value + ", completed$value=" + this.completed$value + ", lastTakenAt=" + this.lastTakenAt + ", snoozeMinutes$value=" + this.snoozeMinutes$value + ", user=" + this.user + ", medicine=" + this.medicine + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Reminder.ReminderBuilder builder() {
        return new Reminder.ReminderBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    public Frequency getFrequency() {
        return this.frequency;
    }

    @java.lang.SuppressWarnings("all")
    public List<LocalTime> getReminderTimes() {
        return this.reminderTimes;
    }

    @java.lang.SuppressWarnings("all")
    public List<DayOfWeek> getDaysOfWeek() {
        return this.daysOfWeek;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getStartDate() {
        return this.startDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getEndDate() {
        return this.endDate;
    }

    @java.lang.SuppressWarnings("all")
    public Double getDoseAmount() {
        return this.doseAmount;
    }

    @java.lang.SuppressWarnings("all")
    public String getDoseUnit() {
        return this.doseUnit;
    }

    @java.lang.SuppressWarnings("all")
    public NotificationType getNotificationType() {
        return this.notificationType;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isCompleted() {
        return this.completed;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastTakenAt() {
        return this.lastTakenAt;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSnoozeMinutes() {
        return this.snoozeMinutes;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public Medicine getMedicine() {
        return this.medicine;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    public void setFrequency(final Frequency frequency) {
        this.frequency = frequency;
    }

    @java.lang.SuppressWarnings("all")
    public void setReminderTimes(final List<LocalTime> reminderTimes) {
        this.reminderTimes = reminderTimes;
    }

    @java.lang.SuppressWarnings("all")
    public void setDaysOfWeek(final List<DayOfWeek> daysOfWeek) {
        this.daysOfWeek = daysOfWeek;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoseAmount(final Double doseAmount) {
        this.doseAmount = doseAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoseUnit(final String doseUnit) {
        this.doseUnit = doseUnit;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotificationType(final NotificationType notificationType) {
        this.notificationType = notificationType;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompleted(final boolean completed) {
        this.completed = completed;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastTakenAt(final LocalDateTime lastTakenAt) {
        this.lastTakenAt = lastTakenAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setSnoozeMinutes(final Integer snoozeMinutes) {
        this.snoozeMinutes = snoozeMinutes;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicine(final Medicine medicine) {
        this.medicine = medicine;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public Reminder() {
        this.reminderTimes = Reminder.$default$reminderTimes();
        this.daysOfWeek = Reminder.$default$daysOfWeek();
        this.notificationType = Reminder.$default$notificationType();
        this.active = Reminder.$default$active();
        this.completed = Reminder.$default$completed();
        this.snoozeMinutes = Reminder.$default$snoozeMinutes();
    }

    @java.lang.SuppressWarnings("all")
    public Reminder(final Long id, final String title, final String notes, final Frequency frequency, final List<LocalTime> reminderTimes, final List<DayOfWeek> daysOfWeek, final LocalDate startDate, final LocalDate endDate, final Double doseAmount, final String doseUnit, final NotificationType notificationType, final boolean active, final boolean completed, final LocalDateTime lastTakenAt, final Integer snoozeMinutes, final User user, final Medicine medicine, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.title = title;
        this.notes = notes;
        this.frequency = frequency;
        this.reminderTimes = reminderTimes;
        this.daysOfWeek = daysOfWeek;
        this.startDate = startDate;
        this.endDate = endDate;
        this.doseAmount = doseAmount;
        this.doseUnit = doseUnit;
        this.notificationType = notificationType;
        this.active = active;
        this.completed = completed;
        this.lastTakenAt = lastTakenAt;
        this.snoozeMinutes = snoozeMinutes;
        this.user = user;
        this.medicine = medicine;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
