// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "users", uniqueConstraints = {@UniqueConstraint(columnNames = "email"), @UniqueConstraint(columnNames = "username")})
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotBlank
    @Size(min = 3, max = 50)
    @Column(nullable = false, unique = true)
    private String username;
    @NotBlank
    @Email
    @Column(nullable = false, unique = true)
    private String email;
    @NotBlank
    @Size(min = 8)
    @Column(nullable = false)
    private String password;
    @Column(name = "full_name")
    private String fullName;
    @Column(name = "phone_number")
    private String phoneNumber;
    @Column(name = "fcm_token", length = 512)
    private String fcmToken;
    @Column(name = "date_of_birth")
    private String dateOfBirth;
    @Column(name = "profile_picture")
    private String profilePicture;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;
    @Column(name = "is_active")
    private boolean active;
    @Column(name = "email_verified")
    private boolean emailVerified;
    @Column(name = "notification_enabled")
    private boolean notificationEnabled;
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Medicine> medicines;
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Reminder> reminders;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;


    public enum Role {
        USER, ADMIN, PHARMACIST;
    }

    @java.lang.SuppressWarnings("all")
    private static Role $default$role() {
        return Role.USER;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$active() {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$emailVerified() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    private static boolean $default$notificationEnabled() {
        return true;
    }

    @java.lang.SuppressWarnings("all")
    private static List<Medicine> $default$medicines() {
        return new ArrayList<>();
    }

    @java.lang.SuppressWarnings("all")
    private static List<Reminder> $default$reminders() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    public static class UserBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String username;
        @java.lang.SuppressWarnings("all")
        private String email;
        @java.lang.SuppressWarnings("all")
        private String password;
        @java.lang.SuppressWarnings("all")
        private String fullName;
        @java.lang.SuppressWarnings("all")
        private String phoneNumber;
        @java.lang.SuppressWarnings("all")
        private String fcmToken;
        @java.lang.SuppressWarnings("all")
        private String dateOfBirth;
        @java.lang.SuppressWarnings("all")
        private String profilePicture;
        @java.lang.SuppressWarnings("all")
        private boolean role$set;
        @java.lang.SuppressWarnings("all")
        private Role role$value;
        @java.lang.SuppressWarnings("all")
        private boolean active$set;
        @java.lang.SuppressWarnings("all")
        private boolean active$value;
        @java.lang.SuppressWarnings("all")
        private boolean emailVerified$set;
        @java.lang.SuppressWarnings("all")
        private boolean emailVerified$value;
        @java.lang.SuppressWarnings("all")
        private boolean notificationEnabled$set;
        @java.lang.SuppressWarnings("all")
        private boolean notificationEnabled$value;
        @java.lang.SuppressWarnings("all")
        private boolean medicines$set;
        @java.lang.SuppressWarnings("all")
        private List<Medicine> medicines$value;
        @java.lang.SuppressWarnings("all")
        private boolean reminders$set;
        @java.lang.SuppressWarnings("all")
        private List<Reminder> reminders$value;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        UserBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder username(final String username) {
            this.username = username;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder password(final String password) {
            this.password = password;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder fullName(final String fullName) {
            this.fullName = fullName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder phoneNumber(final String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder fcmToken(final String fcmToken) {
            this.fcmToken = fcmToken;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder dateOfBirth(final String dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder profilePicture(final String profilePicture) {
            this.profilePicture = profilePicture;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder role(final Role role) {
            this.role$value = role;
            role$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder active(final boolean active) {
            this.active$value = active;
            active$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder emailVerified(final boolean emailVerified) {
            this.emailVerified$value = emailVerified;
            emailVerified$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder notificationEnabled(final boolean notificationEnabled) {
            this.notificationEnabled$value = notificationEnabled;
            notificationEnabled$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder medicines(final List<Medicine> medicines) {
            this.medicines$value = medicines;
            medicines$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder reminders(final List<Reminder> reminders) {
            this.reminders$value = reminders;
            reminders$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public User.UserBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public User build() {
            Role role$value = this.role$value;
            if (!this.role$set) role$value = User.$default$role();
            boolean active$value = this.active$value;
            if (!this.active$set) active$value = User.$default$active();
            boolean emailVerified$value = this.emailVerified$value;
            if (!this.emailVerified$set) emailVerified$value = User.$default$emailVerified();
            boolean notificationEnabled$value = this.notificationEnabled$value;
            if (!this.notificationEnabled$set) notificationEnabled$value = User.$default$notificationEnabled();
            List<Medicine> medicines$value = this.medicines$value;
            if (!this.medicines$set) medicines$value = User.$default$medicines();
            List<Reminder> reminders$value = this.reminders$value;
            if (!this.reminders$set) reminders$value = User.$default$reminders();
            return new User(this.id, this.username, this.email, this.password, this.fullName, this.phoneNumber, this.fcmToken, this.dateOfBirth, this.profilePicture, role$value, active$value, emailVerified$value, notificationEnabled$value, medicines$value, reminders$value, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "User.UserBuilder(id=" + this.id + ", username=" + this.username + ", email=" + this.email + ", password=" + this.password + ", fullName=" + this.fullName + ", phoneNumber=" + this.phoneNumber + ", dateOfBirth=" + this.dateOfBirth + ", profilePicture=" + this.profilePicture + ", role$value=" + this.role$value + ", active$value=" + this.active$value + ", emailVerified$value=" + this.emailVerified$value + ", notificationEnabled$value=" + this.notificationEnabled$value + ", medicines$value=" + this.medicines$value + ", reminders$value=" + this.reminders$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static User.UserBuilder builder() {
        return new User.UserBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getFcmToken() {
        return this.fcmToken;
    }

    @java.lang.SuppressWarnings("all")
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }

    @java.lang.SuppressWarnings("all")
    public String getProfilePicture() {
        return this.profilePicture;
    }

    @java.lang.SuppressWarnings("all")
    public Role getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isEmailVerified() {
        return this.emailVerified;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isNotificationEnabled() {
        return this.notificationEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public List<Medicine> getMedicines() {
        return this.medicines;
    }

    @java.lang.SuppressWarnings("all")
    public List<Reminder> getReminders() {
        return this.reminders;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setFcmToken(final String fcmToken) {
        this.fcmToken = fcmToken;
    }

    @java.lang.SuppressWarnings("all")
    public void setDateOfBirth(final String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @java.lang.SuppressWarnings("all")
    public void setProfilePicture(final String profilePicture) {
        this.profilePicture = profilePicture;
    }

    @java.lang.SuppressWarnings("all")
    public void setRole(final Role role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmailVerified(final boolean emailVerified) {
        this.emailVerified = emailVerified;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotificationEnabled(final boolean notificationEnabled) {
        this.notificationEnabled = notificationEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicines(final List<Medicine> medicines) {
        this.medicines = medicines;
    }

    @java.lang.SuppressWarnings("all")
    public void setReminders(final List<Reminder> reminders) {
        this.reminders = reminders;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public User() {
        this.role = User.$default$role();
        this.active = User.$default$active();
        this.emailVerified = User.$default$emailVerified();
        this.notificationEnabled = User.$default$notificationEnabled();
        this.medicines = User.$default$medicines();
        this.reminders = User.$default$reminders();
    }

    @java.lang.SuppressWarnings("all")
    public User(final Long id, final String username, final String email, final String password, final String fullName, final String phoneNumber, final String fcmToken, final String dateOfBirth, final String profilePicture, final Role role, final boolean active, final boolean emailVerified, final boolean notificationEnabled, final List<Medicine> medicines, final List<Reminder> reminders, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.password = password;
        this.fullName = fullName;
        this.phoneNumber = phoneNumber;
        this.fcmToken = fcmToken;
        this.dateOfBirth = dateOfBirth;
        this.profilePicture = profilePicture;
        this.role = role;
        this.active = active;
        this.emailVerified = emailVerified;
        this.notificationEnabled = notificationEnabled;
        this.medicines = medicines;
        this.reminders = reminders;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
