// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.service;

import com.smartmedicine.config.JwtTokenProvider;
import com.smartmedicine.dto.*;
import com.smartmedicine.exception.BadRequestException;
import com.smartmedicine.exception.ResourceNotFoundException;
import com.smartmedicine.model.User;
import com.smartmedicine.repository.UserRepository;
import org.modelmapper.ModelMapper;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

@Service
public class AuthService implements UserDetailsService {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AuthService.class);
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtTokenProvider jwtTokenProvider;
    private final ModelMapper modelMapper;

    @Override
    public UserDetails loadUserByUsername(String usernameOrEmail) throws UsernameNotFoundException {
        User user = userRepository.findByUsernameOrEmail(usernameOrEmail, usernameOrEmail).orElseThrow(() -> new UsernameNotFoundException("User not found with username or email: " + usernameOrEmail));
        return org.springframework.security.core.userdetails.User.builder().username(user.getUsername()).password(user.getPassword()).authorities(List.of(new SimpleGrantedAuthority("ROLE_" + user.getRole().name()))).accountExpired(!user.isActive()).credentialsExpired(false).disabled(!user.isActive()).accountLocked(!user.isActive()).build();
    }

    @Transactional
    public AuthResponse register(RegisterRequest request) {
        if (userRepository.existsByUsername(request.getUsername())) {
            throw new BadRequestException("Username \'" + request.getUsername() + "\' is already taken");
        }
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new BadRequestException("Email \'" + request.getEmail() + "\' is already registered");
        }
        if (!request.getPassword().equals(request.getConfirmPassword())) {
            throw new BadRequestException("Passwords do not match");
        }
        User user = User.builder().username(request.getUsername()).email(request.getEmail()).password(passwordEncoder.encode(request.getPassword())).fullName(request.getFullName()).phoneNumber(request.getPhoneNumber()).role(User.Role.USER).active(true).build();
        user = userRepository.save(user);
        log.info("New user registered: {}", user.getUsername());
        UserDetails userDetails = loadUserByUsername(user.getUsername());
        String accessToken = jwtTokenProvider.generateToken(userDetails);
        String refreshToken = jwtTokenProvider.generateRefreshToken(userDetails);
        return AuthResponse.builder().accessToken(accessToken).refreshToken(refreshToken).expiresIn(jwtTokenProvider.getJwtExpiration()).user(modelMapper.map(user, UserDTO.class)).build();
    }

    public AuthResponse login(LoginRequest request, AuthenticationManager authenticationManager) {
        Authentication authentication = authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(request.getUsernameOrEmail(), request.getPassword()));
        SecurityContextHolder.getContext().setAuthentication(authentication);
        User user = userRepository.findByUsernameOrEmail(request.getUsernameOrEmail(), request.getUsernameOrEmail()).orElseThrow(() -> new ResourceNotFoundException("User", "usernameOrEmail", request.getUsernameOrEmail()));
        UserDetails userDetails = (UserDetails) authentication.getPrincipal();
        String accessToken = jwtTokenProvider.generateToken(userDetails);
        String refreshToken = jwtTokenProvider.generateRefreshToken(userDetails);
        log.info("User logged in: {}", user.getUsername());
        return AuthResponse.builder().accessToken(accessToken).refreshToken(refreshToken).expiresIn(jwtTokenProvider.getJwtExpiration()).user(modelMapper.map(user, UserDTO.class)).build();
    }

    public AuthResponse refreshToken(String refreshToken) {
        String username = jwtTokenProvider.extractUsername(refreshToken);
        UserDetails userDetails = loadUserByUsername(username);
        if (!jwtTokenProvider.isTokenValid(refreshToken, userDetails)) {
            throw new BadRequestException("Invalid or expired refresh token");
        }
        String newAccessToken = jwtTokenProvider.generateToken(userDetails);
        String newRefreshToken = jwtTokenProvider.generateRefreshToken(userDetails);
        User user = userRepository.findByUsername(username).orElseThrow(() -> new ResourceNotFoundException("User", "username", username));
        return AuthResponse.builder().accessToken(newAccessToken).refreshToken(newRefreshToken).expiresIn(jwtTokenProvider.getJwtExpiration()).user(modelMapper.map(user, UserDTO.class)).build();
    }

    public User getCurrentUser() {
        String username = SecurityContextHolder.getContext().getAuthentication().getName();
        return userRepository.findByUsername(username).orElseThrow(() -> new ResourceNotFoundException("User", "username", username));
    }

    @java.lang.SuppressWarnings("all")
    public AuthService(final UserRepository userRepository, final PasswordEncoder passwordEncoder, final JwtTokenProvider jwtTokenProvider, final ModelMapper modelMapper) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtTokenProvider = jwtTokenProvider;
        this.modelMapper = modelMapper;
    }
}
