// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.service;

import com.smartmedicine.dto.ReminderDTO;
import com.smartmedicine.exception.ResourceNotFoundException;
import com.smartmedicine.model.Medicine;
import com.smartmedicine.model.Reminder;
import com.smartmedicine.model.User;
import com.smartmedicine.repository.MedicineRepository;
import com.smartmedicine.repository.ReminderRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
// import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

@Service
@Transactional(readOnly = true)
public class ReminderService {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ReminderService.class);
    private final ReminderRepository reminderRepository;
    private final MedicineRepository medicineRepository;
    // private final FcmNotificationService fcmNotificationService;
    private final EmailService emailService;

    @Transactional
    public ReminderDTO createReminder(ReminderDTO dto, User currentUser) {
        Reminder reminder = new Reminder();
        reminder.setTitle(dto.getTitle());
        reminder.setNotes(dto.getNotes());
        reminder.setFrequency(dto.getFrequency());
        reminder.setReminderTimes(dto.getReminderTimes());
        reminder.setDaysOfWeek(dto.getDaysOfWeek());
        reminder.setStartDate(dto.getStartDate());
        reminder.setEndDate(dto.getEndDate());
        reminder.setDoseAmount(dto.getDoseAmount());
        reminder.setDoseUnit(dto.getDoseUnit());
        reminder.setNotificationType(dto.getNotificationType() != null ? dto.getNotificationType() : Reminder.NotificationType.PUSH);
        reminder.setSnoozeMinutes(dto.getSnoozeMinutes() != null ? dto.getSnoozeMinutes() : 10);
        reminder.setActive(true);
        reminder.setUser(currentUser);
        if (dto.getMedicineId() != null) {
            Medicine medicine = medicineRepository.findByIdAndUserId(dto.getMedicineId(), currentUser.getId()).orElseThrow(() -> new ResourceNotFoundException("Medicine", "id", dto.getMedicineId()));
            reminder.setMedicine(medicine);
        }
        reminder = reminderRepository.save(reminder);
        log.info("Reminder created: {} for user: {}", reminder.getTitle(), currentUser.getUsername());
        return toDTO(reminder);
    }

    public ReminderDTO getReminderById(Long id, Long userId) {
        Reminder reminder = reminderRepository.findByIdAndUserId(id, userId).orElseThrow(() -> new ResourceNotFoundException("Reminder", "id", id));
        return toDTO(reminder);
    }

    public Page<ReminderDTO> getUserReminders(Long userId, Pageable pageable) {
        return reminderRepository.findByUserId(userId, pageable).map(this::toDTO);
    }

    public List<ReminderDTO> getActiveReminders(Long userId) {
        return reminderRepository.findByUserIdAndActive(userId, true).stream().map(this::toDTO).collect(Collectors.toList());
    }

    public List<ReminderDTO> getTodayReminders(Long userId) {
        return reminderRepository.findActiveRemindersForToday(userId, LocalDate.now()).stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Transactional
    public ReminderDTO updateReminder(Long id, ReminderDTO dto, User currentUser) {
        Reminder reminder = reminderRepository.findByIdAndUserId(id, currentUser.getId()).orElseThrow(() -> new ResourceNotFoundException("Reminder", "id", id));
        reminder.setTitle(dto.getTitle());
        reminder.setNotes(dto.getNotes());
        reminder.setFrequency(dto.getFrequency());
        if (dto.getReminderTimes() != null) reminder.setReminderTimes(dto.getReminderTimes());
        if (dto.getDaysOfWeek() != null) reminder.setDaysOfWeek(dto.getDaysOfWeek());
        if (dto.getStartDate() != null) reminder.setStartDate(dto.getStartDate());
        reminder.setEndDate(dto.getEndDate());
        if (dto.getDoseAmount() != null) reminder.setDoseAmount(dto.getDoseAmount());
        if (dto.getDoseUnit() != null) reminder.setDoseUnit(dto.getDoseUnit());
        if (dto.getNotificationType() != null) reminder.setNotificationType(dto.getNotificationType());
        if (dto.getSnoozeMinutes() != null) reminder.setSnoozeMinutes(dto.getSnoozeMinutes());
        if (dto.getMedicineId() != null) {
            Medicine medicine = medicineRepository.findByIdAndUserId(dto.getMedicineId(), currentUser.getId()).orElseThrow(() -> new ResourceNotFoundException("Medicine", "id", dto.getMedicineId()));
            reminder.setMedicine(medicine);
        }
        reminder = reminderRepository.save(reminder);
        return toDTO(reminder);
    }

    @Transactional
    public ReminderDTO markAsTaken(Long id, Long userId) {
        Reminder reminder = reminderRepository.findByIdAndUserId(id, userId).orElseThrow(() -> new ResourceNotFoundException("Reminder", "id", id));
        reminder.setLastTakenAt(LocalDateTime.now());
        reminder = reminderRepository.save(reminder);
        log.info("Reminder {} marked as taken by user {}", id, userId);
        return toDTO(reminder);
    }

    @Transactional
    public ReminderDTO toggleActive(Long id, Long userId) {
        Reminder reminder = reminderRepository.findByIdAndUserId(id, userId).orElseThrow(() -> new ResourceNotFoundException("Reminder", "id", id));
        reminder.setActive(!reminder.isActive());
        return toDTO(reminderRepository.save(reminder));
    }

    @Transactional
    public void deleteReminder(Long id, Long userId) {
        if (!reminderRepository.existsByIdAndUserId(id, userId)) {
            throw new ResourceNotFoundException("Reminder", "id", id);
        }
        reminderRepository.deleteById(id);
        log.info("Reminder {} deleted by user {}", id, userId);
    }

    /**
     * Scheduled task: check for due reminders every minute at the 1st second.
     * Using cron to prevent drift from fixedDelay.
     */
    @Scheduled(cron = "1 * * * * *")
    public void checkDueReminders() {
        List<Reminder> activeReminders = reminderRepository.findAllActiveRemindersForToday(LocalDate.now());
        log.debug("Checking {} active reminders for notifications", activeReminders.size());

        LocalTime now = LocalTime.now();
        log.debug("Current system time: {}:{}:{} (ms: {})", 
            now.getHour(), now.getMinute(), now.getSecond(), now.getNano() / 1000000);

        for (Reminder reminder : activeReminders) {
            User user = reminder.getUser();
            log.debug("Checking reminder '{}' for user '{}' (Notifications: {}, Email: {}, FCM: {})", 
                reminder.getTitle(), user.getUsername(), user.isNotificationEnabled(), user.getEmail(), user.getFcmToken());

            if (!user.isNotificationEnabled()) {
                log.debug("Skipping: User notifications are disabled");
                continue;
            }

            // Check if any of the reminder's scheduled times matches the current minute
            boolean isDue = false;
            if (reminder.getReminderTimes() != null) {
                for (LocalTime t : reminder.getReminderTimes()) {
                    if (t != null) {
                        log.debug("Comparing scheduled time {}:{} with current time {}:{}", 
                            t.getHour(), t.getMinute(), now.getHour(), now.getMinute());
                        if (t.getHour() == now.getHour() && t.getMinute() == now.getMinute()) {
                            isDue = true;
                            break;
                        }
                    }
                }
            }

            if (isDue) {
                String medicineName = reminder.getMedicine() != null
                        ? reminder.getMedicine().getName() : "medicine";
                /* 
                String title = "💊 Time for your dose!";
                String body = reminder.getTitle() + " – " + medicineName;
                */

                /* 
                // 1. Send Push Notification (if token exists)
                String fcmToken = user.getFcmToken();
                if (fcmToken != null && !fcmToken.isBlank()) {
                    boolean sent = fcmNotificationService.sendNotification(fcmToken, title, body);
                    log.info("FCM notification for reminder '{}' (user {}): sent={}",
                            reminder.getTitle(), user.getUsername(), sent);
                }
                */

                // 2. Send Email Notification
                if (user.getEmail() != null && !user.getEmail().isBlank()) {
                    emailService.sendReminderEmail(user.getEmail(), 
                        user.getFullName() != null ? user.getFullName() : user.getUsername(), 
                        medicineName, reminder.getTitle());
                }
            }
        }
    }

    private ReminderDTO toDTO(Reminder reminder) {
        ReminderDTO dto = new ReminderDTO();
        dto.setId(reminder.getId());
        dto.setTitle(reminder.getTitle());
        dto.setNotes(reminder.getNotes());
        dto.setFrequency(reminder.getFrequency());
        dto.setReminderTimes(reminder.getReminderTimes() != null ? new java.util.ArrayList<>(reminder.getReminderTimes()) : new java.util.ArrayList<>());
        dto.setDaysOfWeek(reminder.getDaysOfWeek() != null ? new java.util.ArrayList<>(reminder.getDaysOfWeek()) : new java.util.ArrayList<>());
        dto.setStartDate(reminder.getStartDate());
        dto.setEndDate(reminder.getEndDate());
        dto.setDoseAmount(reminder.getDoseAmount());
        dto.setDoseUnit(reminder.getDoseUnit());
        dto.setNotificationType(reminder.getNotificationType());
        dto.setActive(reminder.isActive());
        dto.setCompleted(reminder.isCompleted());
        dto.setLastTakenAt(reminder.getLastTakenAt());
        dto.setSnoozeMinutes(reminder.getSnoozeMinutes());
        dto.setUserId(reminder.getUser().getId());
        dto.setCreatedAt(reminder.getCreatedAt());
        dto.setUpdatedAt(reminder.getUpdatedAt());
        if (reminder.getMedicine() != null) {
            dto.setMedicineId(reminder.getMedicine().getId());
            dto.setMedicineName(reminder.getMedicine().getName());
            dto.setMedicineImageUrl(reminder.getMedicine().getImageUrl());
        }
        return dto;
    }

    @java.lang.SuppressWarnings("all")
    public ReminderService(final ReminderRepository reminderRepository, final MedicineRepository medicineRepository, final EmailService emailService) {
        this.reminderRepository = reminderRepository;
        this.medicineRepository = medicineRepository;
        this.emailService = emailService;
    }
}
