// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.dto;

import jakarta.validation.constraints.NotBlank;

public class LoginRequest {
    @NotBlank(message = "Username or email is required")
    private String usernameOrEmail;
    @NotBlank(message = "Password is required")
    private String password;
    private boolean rememberMe = false;

    @java.lang.SuppressWarnings("all")
    public String getUsernameOrEmail() {
        return this.usernameOrEmail;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isRememberMe() {
        return this.rememberMe;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsernameOrEmail(final String usernameOrEmail) {
        this.usernameOrEmail = usernameOrEmail;
    }

    @java.lang.SuppressWarnings("all")
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    public void setRememberMe(final boolean rememberMe) {
        this.rememberMe = rememberMe;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LoginRequest)) return false;
        final LoginRequest other = (LoginRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isRememberMe() != other.isRememberMe()) return false;
        final java.lang.Object this$usernameOrEmail = this.getUsernameOrEmail();
        final java.lang.Object other$usernameOrEmail = other.getUsernameOrEmail();
        if (this$usernameOrEmail == null ? other$usernameOrEmail != null : !this$usernameOrEmail.equals(other$usernameOrEmail)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LoginRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isRememberMe() ? 79 : 97);
        final java.lang.Object $usernameOrEmail = this.getUsernameOrEmail();
        result = result * PRIME + ($usernameOrEmail == null ? 43 : $usernameOrEmail.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LoginRequest(usernameOrEmail=" + this.getUsernameOrEmail() + ", password=" + this.getPassword() + ", rememberMe=" + this.isRememberMe() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public LoginRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public LoginRequest(final String usernameOrEmail, final String password, final boolean rememberMe) {
        this.usernameOrEmail = usernameOrEmail;
        this.password = password;
        this.rememberMe = rememberMe;
    }
}
