// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.dto;

import com.smartmedicine.model.Medicine;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class MedicineDTO {
    private Long id;
    @NotBlank(message = "Medicine name is required")
    private String name;
    private String description;
    @NotBlank(message = "Dosage is required")
    private String dosage;
    private String dosageUnit;
    private Medicine.MedicineType medicineType;
    private String manufacturer;
    private String batchNumber;
    private LocalDate expiryDate;
    private LocalDate purchaseDate;
    @Positive(message = "Quantity must be positive")
    private Integer quantity;
    private String quantityUnit;
    private Integer lowStockThreshold;
    private Double price;
    private boolean prescriptionRequired;
    private String sideEffects;
    private String storageInstructions;
    private String imageUrl;
    private String barcode;
    private Medicine.MedicineStatus status;
    private Long userId;
    private String username;
    private boolean expired;
    private boolean lowStock;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;


    @java.lang.SuppressWarnings("all")
    public static class MedicineDTOBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String name;
        @java.lang.SuppressWarnings("all")
        private String description;
        @java.lang.SuppressWarnings("all")
        private String dosage;
        @java.lang.SuppressWarnings("all")
        private String dosageUnit;
        @java.lang.SuppressWarnings("all")
        private Medicine.MedicineType medicineType;
        @java.lang.SuppressWarnings("all")
        private String manufacturer;
        @java.lang.SuppressWarnings("all")
        private String batchNumber;
        @java.lang.SuppressWarnings("all")
        private LocalDate expiryDate;
        @java.lang.SuppressWarnings("all")
        private LocalDate purchaseDate;
        @java.lang.SuppressWarnings("all")
        private Integer quantity;
        @java.lang.SuppressWarnings("all")
        private String quantityUnit;
        @java.lang.SuppressWarnings("all")
        private Integer lowStockThreshold;
        @java.lang.SuppressWarnings("all")
        private Double price;
        @java.lang.SuppressWarnings("all")
        private boolean prescriptionRequired;
        @java.lang.SuppressWarnings("all")
        private String sideEffects;
        @java.lang.SuppressWarnings("all")
        private String storageInstructions;
        @java.lang.SuppressWarnings("all")
        private String imageUrl;
        @java.lang.SuppressWarnings("all")
        private String barcode;
        @java.lang.SuppressWarnings("all")
        private Medicine.MedicineStatus status;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private String username;
        @java.lang.SuppressWarnings("all")
        private boolean expired;
        @java.lang.SuppressWarnings("all")
        private boolean lowStock;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        MedicineDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder dosage(final String dosage) {
            this.dosage = dosage;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder dosageUnit(final String dosageUnit) {
            this.dosageUnit = dosageUnit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder medicineType(final Medicine.MedicineType medicineType) {
            this.medicineType = medicineType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder manufacturer(final String manufacturer) {
            this.manufacturer = manufacturer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder batchNumber(final String batchNumber) {
            this.batchNumber = batchNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder expiryDate(final LocalDate expiryDate) {
            this.expiryDate = expiryDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder purchaseDate(final LocalDate purchaseDate) {
            this.purchaseDate = purchaseDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder quantity(final Integer quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder quantityUnit(final String quantityUnit) {
            this.quantityUnit = quantityUnit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder lowStockThreshold(final Integer lowStockThreshold) {
            this.lowStockThreshold = lowStockThreshold;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder price(final Double price) {
            this.price = price;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder prescriptionRequired(final boolean prescriptionRequired) {
            this.prescriptionRequired = prescriptionRequired;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder sideEffects(final String sideEffects) {
            this.sideEffects = sideEffects;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder storageInstructions(final String storageInstructions) {
            this.storageInstructions = storageInstructions;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder barcode(final String barcode) {
            this.barcode = barcode;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder status(final Medicine.MedicineStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder username(final String username) {
            this.username = username;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder expired(final boolean expired) {
            this.expired = expired;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder lowStock(final boolean lowStock) {
            this.lowStock = lowStock;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public MedicineDTO.MedicineDTOBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public MedicineDTO build() {
            return new MedicineDTO(this.id, this.name, this.description, this.dosage, this.dosageUnit, this.medicineType, this.manufacturer, this.batchNumber, this.expiryDate, this.purchaseDate, this.quantity, this.quantityUnit, this.lowStockThreshold, this.price, this.prescriptionRequired, this.sideEffects, this.storageInstructions, this.imageUrl, this.barcode, this.status, this.userId, this.username, this.expired, this.lowStock, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "MedicineDTO.MedicineDTOBuilder(id=" + this.id + ", name=" + this.name + ", description=" + this.description + ", dosage=" + this.dosage + ", dosageUnit=" + this.dosageUnit + ", medicineType=" + this.medicineType + ", manufacturer=" + this.manufacturer + ", batchNumber=" + this.batchNumber + ", expiryDate=" + this.expiryDate + ", purchaseDate=" + this.purchaseDate + ", quantity=" + this.quantity + ", quantityUnit=" + this.quantityUnit + ", lowStockThreshold=" + this.lowStockThreshold + ", price=" + this.price + ", prescriptionRequired=" + this.prescriptionRequired + ", sideEffects=" + this.sideEffects + ", storageInstructions=" + this.storageInstructions + ", imageUrl=" + this.imageUrl + ", barcode=" + this.barcode + ", status=" + this.status + ", userId=" + this.userId + ", username=" + this.username + ", expired=" + this.expired + ", lowStock=" + this.lowStock + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static MedicineDTO.MedicineDTOBuilder builder() {
        return new MedicineDTO.MedicineDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getDosage() {
        return this.dosage;
    }

    @java.lang.SuppressWarnings("all")
    public String getDosageUnit() {
        return this.dosageUnit;
    }

    @java.lang.SuppressWarnings("all")
    public Medicine.MedicineType getMedicineType() {
        return this.medicineType;
    }

    @java.lang.SuppressWarnings("all")
    public String getManufacturer() {
        return this.manufacturer;
    }

    @java.lang.SuppressWarnings("all")
    public String getBatchNumber() {
        return this.batchNumber;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getExpiryDate() {
        return this.expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getPurchaseDate() {
        return this.purchaseDate;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    public String getQuantityUnit() {
        return this.quantityUnit;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getLowStockThreshold() {
        return this.lowStockThreshold;
    }

    @java.lang.SuppressWarnings("all")
    public Double getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isPrescriptionRequired() {
        return this.prescriptionRequired;
    }

    @java.lang.SuppressWarnings("all")
    public String getSideEffects() {
        return this.sideEffects;
    }

    @java.lang.SuppressWarnings("all")
    public String getStorageInstructions() {
        return this.storageInstructions;
    }

    @java.lang.SuppressWarnings("all")
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getBarcode() {
        return this.barcode;
    }

    @java.lang.SuppressWarnings("all")
    public Medicine.MedicineStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isExpired() {
        return this.expired;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isLowStock() {
        return this.lowStock;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setDosage(final String dosage) {
        this.dosage = dosage;
    }

    @java.lang.SuppressWarnings("all")
    public void setDosageUnit(final String dosageUnit) {
        this.dosageUnit = dosageUnit;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicineType(final Medicine.MedicineType medicineType) {
        this.medicineType = medicineType;
    }

    @java.lang.SuppressWarnings("all")
    public void setManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @java.lang.SuppressWarnings("all")
    public void setBatchNumber(final String batchNumber) {
        this.batchNumber = batchNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiryDate(final LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setPurchaseDate(final LocalDate purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuantityUnit(final String quantityUnit) {
        this.quantityUnit = quantityUnit;
    }

    @java.lang.SuppressWarnings("all")
    public void setLowStockThreshold(final Integer lowStockThreshold) {
        this.lowStockThreshold = lowStockThreshold;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrice(final Double price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrescriptionRequired(final boolean prescriptionRequired) {
        this.prescriptionRequired = prescriptionRequired;
    }

    @java.lang.SuppressWarnings("all")
    public void setSideEffects(final String sideEffects) {
        this.sideEffects = sideEffects;
    }

    @java.lang.SuppressWarnings("all")
    public void setStorageInstructions(final String storageInstructions) {
        this.storageInstructions = storageInstructions;
    }

    @java.lang.SuppressWarnings("all")
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setBarcode(final String barcode) {
        this.barcode = barcode;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Medicine.MedicineStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpired(final boolean expired) {
        this.expired = expired;
    }

    @java.lang.SuppressWarnings("all")
    public void setLowStock(final boolean lowStock) {
        this.lowStock = lowStock;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MedicineDTO)) return false;
        final MedicineDTO other = (MedicineDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isPrescriptionRequired() != other.isPrescriptionRequired()) return false;
        if (this.isExpired() != other.isExpired()) return false;
        if (this.isLowStock() != other.isLowStock()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$quantity = this.getQuantity();
        final java.lang.Object other$quantity = other.getQuantity();
        if (this$quantity == null ? other$quantity != null : !this$quantity.equals(other$quantity)) return false;
        final java.lang.Object this$lowStockThreshold = this.getLowStockThreshold();
        final java.lang.Object other$lowStockThreshold = other.getLowStockThreshold();
        if (this$lowStockThreshold == null ? other$lowStockThreshold != null : !this$lowStockThreshold.equals(other$lowStockThreshold)) return false;
        final java.lang.Object this$price = this.getPrice();
        final java.lang.Object other$price = other.getPrice();
        if (this$price == null ? other$price != null : !this$price.equals(other$price)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$dosage = this.getDosage();
        final java.lang.Object other$dosage = other.getDosage();
        if (this$dosage == null ? other$dosage != null : !this$dosage.equals(other$dosage)) return false;
        final java.lang.Object this$dosageUnit = this.getDosageUnit();
        final java.lang.Object other$dosageUnit = other.getDosageUnit();
        if (this$dosageUnit == null ? other$dosageUnit != null : !this$dosageUnit.equals(other$dosageUnit)) return false;
        final java.lang.Object this$medicineType = this.getMedicineType();
        final java.lang.Object other$medicineType = other.getMedicineType();
        if (this$medicineType == null ? other$medicineType != null : !this$medicineType.equals(other$medicineType)) return false;
        final java.lang.Object this$manufacturer = this.getManufacturer();
        final java.lang.Object other$manufacturer = other.getManufacturer();
        if (this$manufacturer == null ? other$manufacturer != null : !this$manufacturer.equals(other$manufacturer)) return false;
        final java.lang.Object this$batchNumber = this.getBatchNumber();
        final java.lang.Object other$batchNumber = other.getBatchNumber();
        if (this$batchNumber == null ? other$batchNumber != null : !this$batchNumber.equals(other$batchNumber)) return false;
        final java.lang.Object this$expiryDate = this.getExpiryDate();
        final java.lang.Object other$expiryDate = other.getExpiryDate();
        if (this$expiryDate == null ? other$expiryDate != null : !this$expiryDate.equals(other$expiryDate)) return false;
        final java.lang.Object this$purchaseDate = this.getPurchaseDate();
        final java.lang.Object other$purchaseDate = other.getPurchaseDate();
        if (this$purchaseDate == null ? other$purchaseDate != null : !this$purchaseDate.equals(other$purchaseDate)) return false;
        final java.lang.Object this$quantityUnit = this.getQuantityUnit();
        final java.lang.Object other$quantityUnit = other.getQuantityUnit();
        if (this$quantityUnit == null ? other$quantityUnit != null : !this$quantityUnit.equals(other$quantityUnit)) return false;
        final java.lang.Object this$sideEffects = this.getSideEffects();
        final java.lang.Object other$sideEffects = other.getSideEffects();
        if (this$sideEffects == null ? other$sideEffects != null : !this$sideEffects.equals(other$sideEffects)) return false;
        final java.lang.Object this$storageInstructions = this.getStorageInstructions();
        final java.lang.Object other$storageInstructions = other.getStorageInstructions();
        if (this$storageInstructions == null ? other$storageInstructions != null : !this$storageInstructions.equals(other$storageInstructions)) return false;
        final java.lang.Object this$imageUrl = this.getImageUrl();
        final java.lang.Object other$imageUrl = other.getImageUrl();
        if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
        final java.lang.Object this$barcode = this.getBarcode();
        final java.lang.Object other$barcode = other.getBarcode();
        if (this$barcode == null ? other$barcode != null : !this$barcode.equals(other$barcode)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$username = this.getUsername();
        final java.lang.Object other$username = other.getUsername();
        if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MedicineDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isPrescriptionRequired() ? 79 : 97);
        result = result * PRIME + (this.isExpired() ? 79 : 97);
        result = result * PRIME + (this.isLowStock() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $quantity = this.getQuantity();
        result = result * PRIME + ($quantity == null ? 43 : $quantity.hashCode());
        final java.lang.Object $lowStockThreshold = this.getLowStockThreshold();
        result = result * PRIME + ($lowStockThreshold == null ? 43 : $lowStockThreshold.hashCode());
        final java.lang.Object $price = this.getPrice();
        result = result * PRIME + ($price == null ? 43 : $price.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $dosage = this.getDosage();
        result = result * PRIME + ($dosage == null ? 43 : $dosage.hashCode());
        final java.lang.Object $dosageUnit = this.getDosageUnit();
        result = result * PRIME + ($dosageUnit == null ? 43 : $dosageUnit.hashCode());
        final java.lang.Object $medicineType = this.getMedicineType();
        result = result * PRIME + ($medicineType == null ? 43 : $medicineType.hashCode());
        final java.lang.Object $manufacturer = this.getManufacturer();
        result = result * PRIME + ($manufacturer == null ? 43 : $manufacturer.hashCode());
        final java.lang.Object $batchNumber = this.getBatchNumber();
        result = result * PRIME + ($batchNumber == null ? 43 : $batchNumber.hashCode());
        final java.lang.Object $expiryDate = this.getExpiryDate();
        result = result * PRIME + ($expiryDate == null ? 43 : $expiryDate.hashCode());
        final java.lang.Object $purchaseDate = this.getPurchaseDate();
        result = result * PRIME + ($purchaseDate == null ? 43 : $purchaseDate.hashCode());
        final java.lang.Object $quantityUnit = this.getQuantityUnit();
        result = result * PRIME + ($quantityUnit == null ? 43 : $quantityUnit.hashCode());
        final java.lang.Object $sideEffects = this.getSideEffects();
        result = result * PRIME + ($sideEffects == null ? 43 : $sideEffects.hashCode());
        final java.lang.Object $storageInstructions = this.getStorageInstructions();
        result = result * PRIME + ($storageInstructions == null ? 43 : $storageInstructions.hashCode());
        final java.lang.Object $imageUrl = this.getImageUrl();
        result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
        final java.lang.Object $barcode = this.getBarcode();
        result = result * PRIME + ($barcode == null ? 43 : $barcode.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $username = this.getUsername();
        result = result * PRIME + ($username == null ? 43 : $username.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "MedicineDTO(id=" + this.getId() + ", name=" + this.getName() + ", description=" + this.getDescription() + ", dosage=" + this.getDosage() + ", dosageUnit=" + this.getDosageUnit() + ", medicineType=" + this.getMedicineType() + ", manufacturer=" + this.getManufacturer() + ", batchNumber=" + this.getBatchNumber() + ", expiryDate=" + this.getExpiryDate() + ", purchaseDate=" + this.getPurchaseDate() + ", quantity=" + this.getQuantity() + ", quantityUnit=" + this.getQuantityUnit() + ", lowStockThreshold=" + this.getLowStockThreshold() + ", price=" + this.getPrice() + ", prescriptionRequired=" + this.isPrescriptionRequired() + ", sideEffects=" + this.getSideEffects() + ", storageInstructions=" + this.getStorageInstructions() + ", imageUrl=" + this.getImageUrl() + ", barcode=" + this.getBarcode() + ", status=" + this.getStatus() + ", userId=" + this.getUserId() + ", username=" + this.getUsername() + ", expired=" + this.isExpired() + ", lowStock=" + this.isLowStock() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public MedicineDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public MedicineDTO(final Long id, final String name, final String description, final String dosage, final String dosageUnit, final Medicine.MedicineType medicineType, final String manufacturer, final String batchNumber, final LocalDate expiryDate, final LocalDate purchaseDate, final Integer quantity, final String quantityUnit, final Integer lowStockThreshold, final Double price, final boolean prescriptionRequired, final String sideEffects, final String storageInstructions, final String imageUrl, final String barcode, final Medicine.MedicineStatus status, final Long userId, final String username, final boolean expired, final boolean lowStock, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.dosage = dosage;
        this.dosageUnit = dosageUnit;
        this.medicineType = medicineType;
        this.manufacturer = manufacturer;
        this.batchNumber = batchNumber;
        this.expiryDate = expiryDate;
        this.purchaseDate = purchaseDate;
        this.quantity = quantity;
        this.quantityUnit = quantityUnit;
        this.lowStockThreshold = lowStockThreshold;
        this.price = price;
        this.prescriptionRequired = prescriptionRequired;
        this.sideEffects = sideEffects;
        this.storageInstructions = storageInstructions;
        this.imageUrl = imageUrl;
        this.barcode = barcode;
        this.status = status;
        this.userId = userId;
        this.username = username;
        this.expired = expired;
        this.lowStock = lowStock;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
