// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.dto;

import com.smartmedicine.model.Reminder;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;

public class ReminderDTO {
    private Long id;
    @NotBlank(message = "Reminder title is required")
    private String title;
    private String notes;
    @NotNull(message = "Frequency is required")
    private Reminder.Frequency frequency;
    private List<LocalTime> reminderTimes;
    private List<Reminder.DayOfWeek> daysOfWeek;
    @NotNull(message = "Start date is required")
    private LocalDate startDate;
    private LocalDate endDate;
    private Double doseAmount;
    private String doseUnit;
    private Reminder.NotificationType notificationType;
    private boolean active;
    private boolean completed;
    private LocalDateTime lastTakenAt;
    private Integer snoozeMinutes;
    private Long userId;
    private Long medicineId;
    private String medicineName;
    private String medicineImageUrl;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;


    @java.lang.SuppressWarnings("all")
    public static class ReminderDTOBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String title;
        @java.lang.SuppressWarnings("all")
        private String notes;
        @java.lang.SuppressWarnings("all")
        private Reminder.Frequency frequency;
        @java.lang.SuppressWarnings("all")
        private List<LocalTime> reminderTimes;
        @java.lang.SuppressWarnings("all")
        private List<Reminder.DayOfWeek> daysOfWeek;
        @java.lang.SuppressWarnings("all")
        private LocalDate startDate;
        @java.lang.SuppressWarnings("all")
        private LocalDate endDate;
        @java.lang.SuppressWarnings("all")
        private Double doseAmount;
        @java.lang.SuppressWarnings("all")
        private String doseUnit;
        @java.lang.SuppressWarnings("all")
        private Reminder.NotificationType notificationType;
        @java.lang.SuppressWarnings("all")
        private boolean active;
        @java.lang.SuppressWarnings("all")
        private boolean completed;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime lastTakenAt;
        @java.lang.SuppressWarnings("all")
        private Integer snoozeMinutes;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private Long medicineId;
        @java.lang.SuppressWarnings("all")
        private String medicineName;
        @java.lang.SuppressWarnings("all")
        private String medicineImageUrl;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        ReminderDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder frequency(final Reminder.Frequency frequency) {
            this.frequency = frequency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder reminderTimes(final List<LocalTime> reminderTimes) {
            this.reminderTimes = reminderTimes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder daysOfWeek(final List<Reminder.DayOfWeek> daysOfWeek) {
            this.daysOfWeek = daysOfWeek;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder startDate(final LocalDate startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder endDate(final LocalDate endDate) {
            this.endDate = endDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder doseAmount(final Double doseAmount) {
            this.doseAmount = doseAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder doseUnit(final String doseUnit) {
            this.doseUnit = doseUnit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder notificationType(final Reminder.NotificationType notificationType) {
            this.notificationType = notificationType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder active(final boolean active) {
            this.active = active;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder completed(final boolean completed) {
            this.completed = completed;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder lastTakenAt(final LocalDateTime lastTakenAt) {
            this.lastTakenAt = lastTakenAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder snoozeMinutes(final Integer snoozeMinutes) {
            this.snoozeMinutes = snoozeMinutes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder medicineId(final Long medicineId) {
            this.medicineId = medicineId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder medicineName(final String medicineName) {
            this.medicineName = medicineName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder medicineImageUrl(final String medicineImageUrl) {
            this.medicineImageUrl = medicineImageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ReminderDTO.ReminderDTOBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ReminderDTO build() {
            return new ReminderDTO(this.id, this.title, this.notes, this.frequency, this.reminderTimes, this.daysOfWeek, this.startDate, this.endDate, this.doseAmount, this.doseUnit, this.notificationType, this.active, this.completed, this.lastTakenAt, this.snoozeMinutes, this.userId, this.medicineId, this.medicineName, this.medicineImageUrl, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ReminderDTO.ReminderDTOBuilder(id=" + this.id + ", title=" + this.title + ", notes=" + this.notes + ", frequency=" + this.frequency + ", reminderTimes=" + this.reminderTimes + ", daysOfWeek=" + this.daysOfWeek + ", startDate=" + this.startDate + ", endDate=" + this.endDate + ", doseAmount=" + this.doseAmount + ", doseUnit=" + this.doseUnit + ", notificationType=" + this.notificationType + ", active=" + this.active + ", completed=" + this.completed + ", lastTakenAt=" + this.lastTakenAt + ", snoozeMinutes=" + this.snoozeMinutes + ", userId=" + this.userId + ", medicineId=" + this.medicineId + ", medicineName=" + this.medicineName + ", medicineImageUrl=" + this.medicineImageUrl + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static ReminderDTO.ReminderDTOBuilder builder() {
        return new ReminderDTO.ReminderDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    public Reminder.Frequency getFrequency() {
        return this.frequency;
    }

    @java.lang.SuppressWarnings("all")
    public List<LocalTime> getReminderTimes() {
        return this.reminderTimes;
    }

    @java.lang.SuppressWarnings("all")
    public List<Reminder.DayOfWeek> getDaysOfWeek() {
        return this.daysOfWeek;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getStartDate() {
        return this.startDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getEndDate() {
        return this.endDate;
    }

    @java.lang.SuppressWarnings("all")
    public Double getDoseAmount() {
        return this.doseAmount;
    }

    @java.lang.SuppressWarnings("all")
    public String getDoseUnit() {
        return this.doseUnit;
    }

    @java.lang.SuppressWarnings("all")
    public Reminder.NotificationType getNotificationType() {
        return this.notificationType;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isCompleted() {
        return this.completed;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastTakenAt() {
        return this.lastTakenAt;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSnoozeMinutes() {
        return this.snoozeMinutes;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getMedicineId() {
        return this.medicineId;
    }

    @java.lang.SuppressWarnings("all")
    public String getMedicineName() {
        return this.medicineName;
    }

    @java.lang.SuppressWarnings("all")
    public String getMedicineImageUrl() {
        return this.medicineImageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    public void setFrequency(final Reminder.Frequency frequency) {
        this.frequency = frequency;
    }

    @java.lang.SuppressWarnings("all")
    public void setReminderTimes(final List<LocalTime> reminderTimes) {
        this.reminderTimes = reminderTimes;
    }

    @java.lang.SuppressWarnings("all")
    public void setDaysOfWeek(final List<Reminder.DayOfWeek> daysOfWeek) {
        this.daysOfWeek = daysOfWeek;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartDate(final LocalDate startDate) {
        this.startDate = startDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndDate(final LocalDate endDate) {
        this.endDate = endDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoseAmount(final Double doseAmount) {
        this.doseAmount = doseAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoseUnit(final String doseUnit) {
        this.doseUnit = doseUnit;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotificationType(final Reminder.NotificationType notificationType) {
        this.notificationType = notificationType;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompleted(final boolean completed) {
        this.completed = completed;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastTakenAt(final LocalDateTime lastTakenAt) {
        this.lastTakenAt = lastTakenAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setSnoozeMinutes(final Integer snoozeMinutes) {
        this.snoozeMinutes = snoozeMinutes;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicineId(final Long medicineId) {
        this.medicineId = medicineId;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicineName(final String medicineName) {
        this.medicineName = medicineName;
    }

    @java.lang.SuppressWarnings("all")
    public void setMedicineImageUrl(final String medicineImageUrl) {
        this.medicineImageUrl = medicineImageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ReminderDTO)) return false;
        final ReminderDTO other = (ReminderDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isActive() != other.isActive()) return false;
        if (this.isCompleted() != other.isCompleted()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$doseAmount = this.getDoseAmount();
        final java.lang.Object other$doseAmount = other.getDoseAmount();
        if (this$doseAmount == null ? other$doseAmount != null : !this$doseAmount.equals(other$doseAmount)) return false;
        final java.lang.Object this$snoozeMinutes = this.getSnoozeMinutes();
        final java.lang.Object other$snoozeMinutes = other.getSnoozeMinutes();
        if (this$snoozeMinutes == null ? other$snoozeMinutes != null : !this$snoozeMinutes.equals(other$snoozeMinutes)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$medicineId = this.getMedicineId();
        final java.lang.Object other$medicineId = other.getMedicineId();
        if (this$medicineId == null ? other$medicineId != null : !this$medicineId.equals(other$medicineId)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        final java.lang.Object this$frequency = this.getFrequency();
        final java.lang.Object other$frequency = other.getFrequency();
        if (this$frequency == null ? other$frequency != null : !this$frequency.equals(other$frequency)) return false;
        final java.lang.Object this$reminderTimes = this.getReminderTimes();
        final java.lang.Object other$reminderTimes = other.getReminderTimes();
        if (this$reminderTimes == null ? other$reminderTimes != null : !this$reminderTimes.equals(other$reminderTimes)) return false;
        final java.lang.Object this$daysOfWeek = this.getDaysOfWeek();
        final java.lang.Object other$daysOfWeek = other.getDaysOfWeek();
        if (this$daysOfWeek == null ? other$daysOfWeek != null : !this$daysOfWeek.equals(other$daysOfWeek)) return false;
        final java.lang.Object this$startDate = this.getStartDate();
        final java.lang.Object other$startDate = other.getStartDate();
        if (this$startDate == null ? other$startDate != null : !this$startDate.equals(other$startDate)) return false;
        final java.lang.Object this$endDate = this.getEndDate();
        final java.lang.Object other$endDate = other.getEndDate();
        if (this$endDate == null ? other$endDate != null : !this$endDate.equals(other$endDate)) return false;
        final java.lang.Object this$doseUnit = this.getDoseUnit();
        final java.lang.Object other$doseUnit = other.getDoseUnit();
        if (this$doseUnit == null ? other$doseUnit != null : !this$doseUnit.equals(other$doseUnit)) return false;
        final java.lang.Object this$notificationType = this.getNotificationType();
        final java.lang.Object other$notificationType = other.getNotificationType();
        if (this$notificationType == null ? other$notificationType != null : !this$notificationType.equals(other$notificationType)) return false;
        final java.lang.Object this$lastTakenAt = this.getLastTakenAt();
        final java.lang.Object other$lastTakenAt = other.getLastTakenAt();
        if (this$lastTakenAt == null ? other$lastTakenAt != null : !this$lastTakenAt.equals(other$lastTakenAt)) return false;
        final java.lang.Object this$medicineName = this.getMedicineName();
        final java.lang.Object other$medicineName = other.getMedicineName();
        if (this$medicineName == null ? other$medicineName != null : !this$medicineName.equals(other$medicineName)) return false;
        final java.lang.Object this$medicineImageUrl = this.getMedicineImageUrl();
        final java.lang.Object other$medicineImageUrl = other.getMedicineImageUrl();
        if (this$medicineImageUrl == null ? other$medicineImageUrl != null : !this$medicineImageUrl.equals(other$medicineImageUrl)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ReminderDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isActive() ? 79 : 97);
        result = result * PRIME + (this.isCompleted() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $doseAmount = this.getDoseAmount();
        result = result * PRIME + ($doseAmount == null ? 43 : $doseAmount.hashCode());
        final java.lang.Object $snoozeMinutes = this.getSnoozeMinutes();
        result = result * PRIME + ($snoozeMinutes == null ? 43 : $snoozeMinutes.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $medicineId = this.getMedicineId();
        result = result * PRIME + ($medicineId == null ? 43 : $medicineId.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        final java.lang.Object $frequency = this.getFrequency();
        result = result * PRIME + ($frequency == null ? 43 : $frequency.hashCode());
        final java.lang.Object $reminderTimes = this.getReminderTimes();
        result = result * PRIME + ($reminderTimes == null ? 43 : $reminderTimes.hashCode());
        final java.lang.Object $daysOfWeek = this.getDaysOfWeek();
        result = result * PRIME + ($daysOfWeek == null ? 43 : $daysOfWeek.hashCode());
        final java.lang.Object $startDate = this.getStartDate();
        result = result * PRIME + ($startDate == null ? 43 : $startDate.hashCode());
        final java.lang.Object $endDate = this.getEndDate();
        result = result * PRIME + ($endDate == null ? 43 : $endDate.hashCode());
        final java.lang.Object $doseUnit = this.getDoseUnit();
        result = result * PRIME + ($doseUnit == null ? 43 : $doseUnit.hashCode());
        final java.lang.Object $notificationType = this.getNotificationType();
        result = result * PRIME + ($notificationType == null ? 43 : $notificationType.hashCode());
        final java.lang.Object $lastTakenAt = this.getLastTakenAt();
        result = result * PRIME + ($lastTakenAt == null ? 43 : $lastTakenAt.hashCode());
        final java.lang.Object $medicineName = this.getMedicineName();
        result = result * PRIME + ($medicineName == null ? 43 : $medicineName.hashCode());
        final java.lang.Object $medicineImageUrl = this.getMedicineImageUrl();
        result = result * PRIME + ($medicineImageUrl == null ? 43 : $medicineImageUrl.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ReminderDTO(id=" + this.getId() + ", title=" + this.getTitle() + ", notes=" + this.getNotes() + ", frequency=" + this.getFrequency() + ", reminderTimes=" + this.getReminderTimes() + ", daysOfWeek=" + this.getDaysOfWeek() + ", startDate=" + this.getStartDate() + ", endDate=" + this.getEndDate() + ", doseAmount=" + this.getDoseAmount() + ", doseUnit=" + this.getDoseUnit() + ", notificationType=" + this.getNotificationType() + ", active=" + this.isActive() + ", completed=" + this.isCompleted() + ", lastTakenAt=" + this.getLastTakenAt() + ", snoozeMinutes=" + this.getSnoozeMinutes() + ", userId=" + this.getUserId() + ", medicineId=" + this.getMedicineId() + ", medicineName=" + this.getMedicineName() + ", medicineImageUrl=" + this.getMedicineImageUrl() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ReminderDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public ReminderDTO(final Long id, final String title, final String notes, final Reminder.Frequency frequency, final List<LocalTime> reminderTimes, final List<Reminder.DayOfWeek> daysOfWeek, final LocalDate startDate, final LocalDate endDate, final Double doseAmount, final String doseUnit, final Reminder.NotificationType notificationType, final boolean active, final boolean completed, final LocalDateTime lastTakenAt, final Integer snoozeMinutes, final Long userId, final Long medicineId, final String medicineName, final String medicineImageUrl, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.title = title;
        this.notes = notes;
        this.frequency = frequency;
        this.reminderTimes = reminderTimes;
        this.daysOfWeek = daysOfWeek;
        this.startDate = startDate;
        this.endDate = endDate;
        this.doseAmount = doseAmount;
        this.doseUnit = doseUnit;
        this.notificationType = notificationType;
        this.active = active;
        this.completed = completed;
        this.lastTakenAt = lastTakenAt;
        this.snoozeMinutes = snoozeMinutes;
        this.userId = userId;
        this.medicineId = medicineId;
        this.medicineName = medicineName;
        this.medicineImageUrl = medicineImageUrl;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
