// Generated by delombok at Wed Mar 11 11:42:14 IST 2026
package com.smartmedicine.controller;

import com.smartmedicine.dto.ApiResponse;
import com.smartmedicine.dto.UserDTO;
import com.smartmedicine.model.User;
import com.smartmedicine.service.AuthService;
import com.smartmedicine.service.UserService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import java.util.Map;

@RestController
@RequestMapping("/api/users")
@Tag(name = "Users", description = "User management APIs")
@SecurityRequirement(name = "Bearer Authentication")
public class UserController {
    private final UserService userService;
    private final AuthService authService;

    @GetMapping("/profile")
    @Operation(summary = "Get current user\'s profile")
    public ResponseEntity<ApiResponse<UserDTO>> getProfile() {
        User currentUser = authService.getCurrentUser();
        return ResponseEntity.ok(ApiResponse.success(userService.getUserById(currentUser.getId())));
    }

    @PutMapping("/profile")
    @Operation(summary = "Update current user\'s profile")
    public ResponseEntity<ApiResponse<UserDTO>> updateProfile(@Valid @RequestBody UserDTO userDTO) {
        User currentUser = authService.getCurrentUser();
        UserDTO updated = userService.updateProfile(currentUser.getId(), userDTO);
        return ResponseEntity.ok(ApiResponse.success("Profile updated successfully", updated));
    }

    @PostMapping("/change-password")
    @Operation(summary = "Change password")
    public ResponseEntity<ApiResponse<Void>> changePassword(@RequestParam("currentPassword") String currentPassword, @RequestParam("newPassword") String newPassword) {
        User currentUser = authService.getCurrentUser();
        userService.changePassword(currentUser.getId(), currentPassword, newPassword);
        return ResponseEntity.ok(ApiResponse.success("Password changed successfully", null));
    }

    @DeleteMapping("/account")
    @Operation(summary = "Deactivate current user\'s account")
    public ResponseEntity<ApiResponse<Void>> deactivateAccount() {
        User currentUser = authService.getCurrentUser();
        userService.deactivateAccount(currentUser.getId());
        return ResponseEntity.ok(ApiResponse.success("Account deactivated", null));
    }

    // ===== Admin Endpoints =====
    @GetMapping
    @PreAuthorize("hasRole(\'ADMIN\')")
    @Operation(summary = "Get all users (Admin only)")
    public ResponseEntity<ApiResponse<Page<UserDTO>>> getAllUsers(Pageable pageable) {
        return ResponseEntity.ok(ApiResponse.success(userService.getAllUsers(pageable)));
    }

    @GetMapping("/{id}")
    @PreAuthorize("hasRole(\'ADMIN\')")
    @Operation(summary = "Get user by ID (Admin only)")
    public ResponseEntity<ApiResponse<UserDTO>> getUserById(@PathVariable("id") Long id) {
        return ResponseEntity.ok(ApiResponse.success(userService.getUserById(id)));
    }

    @PatchMapping("/{id}/role")
    @PreAuthorize("hasRole(\'ADMIN\')")
    @Operation(summary = "Update user role (Admin only)")
    public ResponseEntity<ApiResponse<UserDTO>> updateUserRole(@PathVariable("id") Long id, @RequestParam("role") User.Role role) {
        return ResponseEntity.ok(ApiResponse.success(userService.updateUserRole(id, role)));
    }

    @GetMapping("/stats")
    @PreAuthorize("hasRole(\'ADMIN\')")
    @Operation(summary = "Get user statistics (Admin only)")
    public ResponseEntity<ApiResponse<Map<String, Long>>> getUserStats() {
        return ResponseEntity.ok(ApiResponse.success(userService.getUserStats()));
    }

    @java.lang.SuppressWarnings("all")
    public UserController(final UserService userService, final AuthService authService) {
        this.userService = userService;
        this.authService = authService;
    }
}
